services:
  - type: web
    name: a11yscan
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BROWSERLESS_WSS
        value: wss://chrome.browserless.io?token=free
