services:
  - type: web
    name: a11yscan
    env: node
    buildCommand: |
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
